String[] ingredients = {"chicken", "breadcrumbs", "salt", "garlic", "lime"};
System.out.println("ORIGINAL");
System.out.println(ingredients[0]);
System.out.println(ingredients[1]);
System.out.println(ingredients[2]);
System.out.println(ingredients[3]);
System.out.println(ingredients[4]);
ingredients[4] = "lemon";
ingredients[2] = "rocket";
System.out.println("AFTER CHANGES");
System.out.println(ingredients[0]);
System.out.println(ingredients[1]);
System.out.println(ingredients[2]);
System.out.println(ingredients[3]);
System.out.println(ingredients[4]);